### PR TITLE
Add some functionalities

### PR DESCRIPTION
**Pull request by mrkwjc**
I added some functions for my startup blog, consider including them to lagom. Possibly mathjax, and email icon should be optional for general template, i added them as fixed feature.

### CODE REVIEW

**Comment by swanson** [comment]
Cool! I'm interesting in adding the email link to the main theme. Could you create a new PR with just those changes (or update this one)? I'm not planning to add MathJax or Disqus to the theme at this time; I think those are more specialized.

**Comment by mrkwjc** [comment]
I'm not sure if it is possible to create pull request for one specific commit. Maybe you can fetch and then checkout only the social.html file?

**Comment by clearnote01** [comment]
@swanson can you re-consider your position on disqus? I think it's would be a really neat feature to have.

**Comment by swanson** [comment]
@clearnote01 This project is a theme -- it covers the styling and structure of a Jekyll site. When you use it, you are forking it into your own repository, so you can add whatever extra functionality you'd like. 

I don't think that the majority of people will want to include Disqus comments out of the box, but those that do want it can add it to their own blogs/sites with modifying the template.

**Pull request closed without merging**
